#!/bin/bash -login

# how long?
#PBS -l walltime=03:00:00 

# how much memory?
#PBS -l mem=10gb

# specify resources needed. 
#PBS -l nodes=1:ppn=4

# email me
#PBS -m abe

# change to current directory
cd $PBS_O_WORKDIR

# add necessary modules
module load GNU/4.9
module load OpenMPI/1.10.0
module load R/3.3.2
module load JAGS/4.2.0


# run R commandline with the Rscript command
Rscript example.R

qstat -f $PBS_JOBID
